[package]
name = "YGOPro3"
version = "0.1.0"
description = "YGOPro by tauriv2.0"
authors = ["jwyxym"]
edition = "2024"

[lib]
name = "ygopro3"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-fs = "2"
tauri-plugin-os = "2"
tauri-plugin-process = "2"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-http = "2"
tauri-plugin-websocket = "2"
tauri-plugin-dialog = "2"
tauri-plugin-dglab-ws-server = "0.1.1"
tauri-plugin-tcp = { git = "https://github.com/jwyxym/tauri-plugin-tcp.git" }
tauri-plugin-ygopro3 = { path = "tauri-plugin-ygopro3" }
