[ot]
0x1 = "OCG"
0x2 = "TCG"
0x3 = "No Exclusive"
0x4 = "Custom"
0x8 = "Simplified Chinese"

[attribute]
0x1 = "Earth"
0x2 = "Water"
0x4 = "Fire"
0x8 = "Wind"
0x10 = "Light"
0x20 = "Dark"
0x40 = "Divine"

[link]
0x40 = "↖"
0x80 = "↑"
0x100 = "↗"
0x8 = "←"
0x20 = "→"
0x1 = "↙"
0x2 = "↓"
0x4 = "↘"

[category]
0x1 = "S/T Destroy"
0x2 = "Destroy Monster"
0x4 = "Banish"
0x8 = "Graveyard"
0x10 = "Back to Hand"
0x20 = "Back to Deck"
0x40 = "Destroy Hand"
0x80 = "Destroy Deck"
0x100 = "Draw"
0x200 = "Search"
0x400 = "Recovery"
0x800 = "Position"
0x1000 = "Control"
0x2000 = "Change ATK/DEF"
0x4000 = "Piercing"
0x8000 = "Repeat Attack"
0x10000 = "Limit Attack"
0x20000 = "Direct Attack"
0x40000 = "Special Summon"
0x80000 = "Token"
0x100000 = "Type-Related"
0x200000 = "Property-Related"
0x400000 = "Damage LP"
0x800000 = "Recover LP"
0x1000000 = "Destroy"
0x2000000 = "Select"
0x4000000 = "Counter"
0x8000000 = "Gamble"
0x10000000 = "Fusion-Related"
0x20000000 = "Tuner-Related"
0x40000000 = "Xyz-Related"
0x80000000 = "Negate Effect"

[race]
0x1 = "Warrior"
0x2 = "Spellcaster"
0x4 = "Fairy"
0x8 = "Fiend"
0x10 = "Zombie"
0x20 = "Machine"
0x40 = "Aqua"
0x80 = "Pyro"
0x100 = "Rock"
0x200 = "Winged Beast"
0x400 = "Plant"
0x800 = "Insect"
0x1000 = "Thunder"
0x2000 = "Dragon"
0x4000 = "Beast"
0x8000 = "Beast-Warrior"
0x10000 = "Dinosaur"
0x20000 = "Fish"
0x40000 = "Sea Serpent"
0x80000 = "Reptile"
0x100000 = "Psychic"
0x200000 = "Divine-Beast"
0x400000 = "Creator God"
0x800000 = "Wyrm"
0x1000000 = "Cyberse"
0x2000000 = "Illusion"

[types]
0x1 = "Monster"
0x10 = "Normal"
0x12 = "Normal (Spell/Trap)"
0x20 = "Effect"
0x1000 = "Tuner"
0x800 = "Gemini"
0x200000 = "Flip"
0x400 = "Union"
0x200 = "Spirit"
0x400000 = "Toon"
0x40 = "Fusion"
0x2000 = "Synchro"
0x800000 = "Xyz"
0x1000000 = "Pendulum"
0x80 = "Ritual"
0x81 = "Ritual (Monster)"
0x82 = "Ritual (Spell/Trap)"
0x2 = "Spell"
0x4 = "Trap"
0x10000 = "Quick-Play"
0x20000 = "Continuous"
0x40000 = "Equip"
0x80000 = "Field"
0x100000 = "Counter"
0x4000000 = "Link"
0x2000000 = "Special Summon"
0x4000 = "Token"
