[ot]
0x1 = "ot_ocg.png"
0x2 = "ot_tcg.png"
0x3 = "ot_ocgtcg.png"
0x4 = "ot_custom.png"
0x8 = "ot_sc.png"

[attribute]
0x1 = "attr_earth.png"
0x2 = "attr_water.png"
0x4 = "attr_fire.png"
0x8 = "attr_wind.png"
0x10 = "attr_light.png"
0x20 = "attr_dark.png"
0x40 = "attr_divine.png"

[link]
0x40 = ["arrow-1-off.png", "arrow-1-on.png"]
0x80 = ["arrow-2-off.png", "arrow-2-on.png"]
0x100 = ["arrow-3-off.png", "arrow-3-on.png"]
0x8 = ["arrow-4-off.png", "arrow-4-on.png"]
0x20 = ["arrow-5-off.png", "arrow-5-on.png"]
0x1 = ["arrow-6-off.png", "arrow-6-on.png"]
0x2 = ["arrow-7-off.png", "arrow-7-on.png"]
0x4 = ["arrow-8-off.png", "arrow-8-on.png"]

[category]
0x1 = "category_destroySpellTrap.png"
0x2 = "category_destroyMonster.png"
0x4 = "category_banish.png"
0x8 = "category_sendToGraveyard.png"
0x10 = "category_returnToHand.png"
0x20 = "category_returnToDeck.png"
0x40 = "category_destroyHand.png"
0x80 = "category_destroyDeck.png"
0x100 = "category_draw.png"
0x200 = "category_search.png"
0x400 = "category_recovery.png"
0x800 = "category_position.png"
0x1000 = "category_control.png"
0x2000 = "category_changeAtkDef.png"
0x4000 = "category_piercing.png"
0x8000 = "category_repeatAttack.png"
0x10000 = "category_limitAttack.png"
0x20000 = "category_directAttack.png"
0x40000 = "category_specialSummon.png"
0x80000 = "category_token.png"
0x100000 = "category_raceRelated.png"
0x200000 = "category_attributeRelated.png"
0x400000 = "category_damageLP.png"
0x800000 = "category_recoverLP.png"
0x1000000 = "category_undestroyable.png"
0x2000000 = "category_ineffective.png"
0x4000000 = "category_counter.png"
0x8000000 = "category_gamble.png"
0x10000000 = "category_fusionRelated.png"
0x20000000 = "category_synchroRelated.png"
0x40000000 = "category_xyzRelated.png"
0x80000000 = "category_negateEffect.png"

[race]
0x1 = "race_warrior.png"
0x2 = "race_spell-caster.png"
0x4 = "race_fairy.png"
0x8 = "race_fiend.png"
0x10 = "race_zombie.png"
0x20 = "race_machine.png"
0x40 = "race_aqua.png"
0x80 = "race_pyro.png"
0x100 = "race_rock.png"
0x200 = "race_wind-beast.png"
0x400 = "race_plant.png"
0x800 = "race_insect.png"
0x1000 = "race_thunder.png"
0x2000 = "race_dragon.png"
0x4000 = "race_beast.png"
0x8000 = "race_beast-warrior.png"
0x10000 = "race_dinosaur.png"
0x20000 = "race_fish.png"
0x40000 = "race_sea-serpent.png"
0x80000 = "race_reptile.png"
0x100000 = "race_psycho.png"
0x200000 = "race_divine-beast.png"
0x400000 = "race_create-god.png"
0x800000 = "race_wyrm.png"
0x1000000 = "race_cyberse.png"
0x2000000 = "race_illusion.png"

[types]
0x1 = "cardType_monster.png"
0x10 = "type_normal.png"
0x12 = "spellTrapType_normal.png"
0x20 = "type_effect.png"
0x1000 = "type_tuner.png"
0x800 = "type_dual.png"
0x200000 = "type_flip.png"
0x400 = "type_union.png"
0x200 = "type_spirit.png"
0x400000 = "type_toon.png"
0x40 = "type_fusion.png"
0x2000 = "type_synchro.png"
0x800000 = "type_xyz.png"
0x1000000 = "type_pendulum.png"
0x80 = "type_ritual.png"
0x81 = "type_ritual.png"
0x82 = "spellTrapType_ritual.png"
0x2 = "cardType_spell.png"
0x4 = "cardType_trap.png"
0x10000 = "spellTrapType_quickplay.png"
0x20000 = "spellTrapType_continuous.png"
0x40000 = "spellTrapType_equip.png"
0x80000 = "spellTrapType_field.png"
0x100000 = "spellTrapType_counter.png"
0x4000000 = "type_link.png"
0x2000000 = "type_specialSummon.png"
0x4000 = "type_token"
[sound]
"BACK_BGM" = "Night View.mp3"
"BATTLE_BGM" = "City of Night.mp3"
[font]
"TITLE" = "优设标题黑.ttf"
"MENU" = "阿里巴巴普惠体.ttf"
"ATK" = "AtkDef.ttf"