[ot]
0x1 = "ot/ot_ocg.png"
0x2 = "ot/ot_tcg.png"
0x3 = "ot/ot_ocgtcg.png"
0x4 = "ot/ot_custom.png"
0x8 = "ot/ot_sc.png"

[attribute]
0x1 = "attribute/attr_earth.png"
0x2 = "attribute/attr_water.png"
0x4 = "attribute/attr_fire.png"
0x8 = "attribute/attr_wind.png"
0x10 = "attribute/attr_light.png"
0x20 = "attribute/attr_dark.png"
0x40 = "attribute/attr_divine.png"

[link]
0x40 = ["arrow/arrow-1-off.png", "arrow/arrow-1-on.png"]
0x80 = ["arrow/arrow-2-off.png", "arrow/arrow-2-on.png"]
0x100 = ["arrow/arrow-3-off.png", "arrow/arrow-3-on.png"]
0x8 = ["arrow/arrow-4-off.png", "arrow/arrow-4-on.png"]
0x20 = ["arrow/arrow-5-off.png", "arrow/arrow-5-on.png"]
0x1 = ["arrow/arrow-6-off.png", "arrow/arrow-6-on.png"]
0x2 = ["arrow/arrow-7-off.png", "arrow/arrow-7-on.png"]
0x4 = ["arrow/arrow-8-off.png", "arrow/arrow-8-on.png"]

[category]
0x1 = "category/category_destroySpellTrap.png"
0x2 = "category/category_destroyMonster.png"
0x4 = "category/category_banish.png"
0x8 = "category/category_sendToGraveyard.png"
0x10 = "category/category_returnToHand.png"
0x20 = "category/category_returnToDeck.png"
0x40 = "category/category_destroyHand.png"
0x80 = "category/category_destroyDeck.png"
0x100 = "category/category_draw.png"
0x200 = "category/category_search.png"
0x400 = "category/category_recovery.png"
0x800 = "category/category_position.png"
0x1000 = "category/category_control.png"
0x2000 = "category/category_changeAtkDef.png"
0x4000 = "category/category_piercing.png"
0x8000 = "category/category_repeatAttack.png"
0x10000 = "category/category_limitAttack.png"
0x20000 = "category/category_directAttack.png"
0x40000 = "category/category_specialSummon.png"
0x80000 = "category/category_token.png"
0x100000 = "category/category_raceRelated.png"
0x200000 = "category/category_attributeRelated.png"
0x400000 = "category/category_damageLP.png"
0x800000 = "category/category_recoverLP.png"
0x1000000 = "category/category_undestroyable.png"
0x2000000 = "category/category_ineffective.png"
0x4000000 = "category/category_counter.png"
0x8000000 = "category/category_gamble.png"
0x10000000 = "category/category_fusionRelated.png"
0x20000000 = "category/category_synchroRelated.png"
0x40000000 = "category/category_xyzRelated.png"
0x80000000 = "category/category_negateEffect.png"

[race]
0x1 = "race/race_warrior.png"
0x2 = "race/race_spell-caster.png"
0x4 = "race/race_fairy.png"
0x8 = "race/race_fiend.png"
0x10 = "race/race_zombie.png"
0x20 = "race/race_machine.png"
0x40 = "race/race_aqua.png"
0x80 = "race/race_pyro.png"
0x100 = "race/race_rock.png"
0x200 = "race/race_wind-beast.png"
0x400 = "race/race_plant.png"
0x800 = "race/race_insect.png"
0x1000 = "race/race_thunder.png"
0x2000 = "race/race_dragon.png"
0x4000 = "race/race_beast.png"
0x8000 = "race/race_beast-warrior.png"
0x10000 = "race/race_dinosaur.png"
0x20000 = "race/race_fish.png"
0x40000 = "race/race_sea-serpent.png"
0x80000 = "race/race_reptile.png"
0x100000 = "race/race_psycho.png"
0x200000 = "race/race_divine-beast.png"
0x400000 = "race/race_create-god.png"
0x800000 = "race/race_wyrm.png"
0x1000000 = "race/race_cyberse.png"
0x2000000 = "race/race_illusion.png"

[types]
0x1 = "type/cardType_monster.png"
0x10 = "type/type_normal.png"
0x12 = "type/spellTrapType_normal.png"
0x20 = "type/type_effect.png"
0x1000 = "type/type_tuner.png"
0x800 = "type/type_dual.png"
0x200000 = "type/type_flip.png"
0x400 = "type/type_union.png"
0x200 = "type/type_spirit.png"
0x400000 = "type/type_toon.png"
0x40 = "type/type_fusion.png"
0x2000 = "type/type_synchro.png"
0x800000 = "type/type_xyz.png"
0x1000000 = "type/type_pendulum.png"
0x80 = "type/type_ritual.png"
0x81 = "type/type_ritual.png"
0x82 = "type/spellTrapType_ritual.png"
0x2 = "type/cardType_spell.png"
0x4 = "type/cardType_trap.png"
0x10000 = "type/spellTrapType_quickplay.png"
0x20000 = "type/spellTrapType_continuous.png"
0x40000 = "type/spellTrapType_equip.png"
0x80000 = "type/spellTrapType_field.png"
0x100000 = "type/spellTrapType_counter.png"
0x4000000 = "type/type_link.png"
0x2000000 = "type/type_specialSummon.png"
0x4000 = "type/type_token.png"

[btn]
"ACTIVATE" = ["btn/btn_activate.png", "btn/btn_hover_activate.png"]
"SCALE" = ["btn/btn_scale.png", "btn/btn_hover_scale.png"]
"ATTACK" = ["btn/btn_attack.png", "btn/btn_hover_attack.png"]
"SUMMON" = ["btn/btn_summon.png", "btn/btn_hover_summon.png"]
"SPSUMMON" = ["btn/btn_spsummon.png", "btn/btn_hover_spsummon.png"]
"PSUMMON" = ["btn/btn_psummon.png", "btn/btn_hover_psummon.png"]
"FLIP" = ["btn/btn_flip.png", "btn/btn_hover_flip.png"]
"MSET" = ["btn/btn_mset.png", "btn/btn_hover_mset.png"]
"SSET" = ["btn/btn_sset.png", "btn/btn_hover_sset.png"]
"POS_ATTACK" = ["btn/btn_pos_attack.png", "btn/btn_hover_pos_attack.png"]
"POS_DEFENCE" = ["btn/btn_pos_defence", "btn/btn_hover_pos_defence.png"]

[info]
"LEVEL" = "info/info_level.png"
"LINK" = "info/info_link.png"
"OVERLAY" = "info/info_overlay.png"
"RANK" = "info/info_rank.png"
"SCALE" = "info/info_scale.png"
"STAR_RANK_LINK" = "info/info_star_rank_link.png"
"TUNER" = "info/info_tuner.png"

[counter]
0x0 = "counter/counter_0.png"
0x1 = "counter/counter_1.png"
0x3 = "counter/counter_3.png"
0x4 = "counter/counter_4.png"
0x5 = "counter/counter_5.png"
0x6 = "counter/counter_6.png"
0x8 = "counter/counter_8.png"
0xa = "counter/counter_a.png"
0xc = "counter/counter_c.png"
0xd = "counter/counter_d.png"
0xf = "counter/counter_f.png"
0x10 = "counter/counter_10.png"
0x11 = "counter/counter_11.png"
0x12 = "counter/counter_12.png"
0x13 = "counter/counter_13.png"
0x16 = "counter/counter_16.png"
0x17 = "counter/counter_17.png"
0x18 = "counter/counter_18.png"
0x1a = "counter/counter_1a.png"
0x1b = "counter/counter_1b.png"
0x1c = "counter/counter_1c.png"
0x1d = "counter/counter_1d.png"
0x1e = "counter/counter_1e.png"
0x20 = "counter/counter_20.png"
0x22 = "counter/counter_22.png"
0x23 = "counter/counter_23.png"
0x25 = "counter/counter_25.png"
0x2b = "counter/counter_2b.png"
0x2c = "counter/counter_2c.png"
0x2e = "counter/counter_2e.png"
0x2f = "counter/counter_2f.png"
0x30 = "counter/counter_30.png"
0x31 = "counter/counter_31.png"
0x32 = "counter/counter_32.png"
0x33 = "counter/counter_33.png"
0x35 = "counter/counter_35.png"
0x36 = "counter/counter_36.png"
0x37 = "counter/counter_37.png"
0x43 = "counter/counter_43.png"
0x4a = "counter/counter_4a.png"
0x4b = "counter/counter_4b.png"
0x4c = "counter/counter_4c.png"
0x56 = "counter/counter_56.png"
0x57 = "counter/counter_57.png"
0x59 = "counter/counter_59.png"
0x5e = "counter/counter_5e.png"
0x5f = "counter/counter_5f.png"
0x64 = "counter/counter_64.png"
0x6a = "counter/counter_6a.png"
0x1002 = "counter/counter_1002.png"
0x1009 = "counter/counter_1009.png"
0x100e = "counter/counter_100e.png"
0x1015 = "counter/counter_1015.png"
0x1019 = "counter/counter_1019.png"
0x1021 = "counter/counter_1021.png"
0x1024 = "counter/counter_1024.png"
0x102a = "counter/counter_102a.png"
0x1038 = "counter/counter_1038.png"
0x1039 = "counter/counter_1039.png"
0x1041 = "counter/counter_1041.png"
0x1045 = "counter/counter_1045.png"
0x1049 = "counter/counter_1049.png"
0x104d = "counter/counter_104d.png"
0x104f = "counter/counter_104f.png"
0x105c = "counter/counter_105c.png"
0x1063 = "counter/counter_1063.png"
0x1065 = "counter/counter_1065.png"
0x1072 = "counter/counter_1072.png"

[avatar]
"AVATAR" = [
    "avatar/avatar_0.png",
    "avatar/avatar_1.png",
    "avatar/avatar_2.png",
    "avatar/avatar_3.png",
    "avatar/avatar_4.png",
    "avatar/avatar_5.png",
    "avatar/avatar_6.png"
]

[other]
"COVER" = "other/cover.jpg"
"UNKNOWN" = "other/unknown.jpg"
"BACKI" = "other/back_I.jpg"
"BACKII" = "other/back_II.jpg"
"S" = "other/s.png"
"R" = "other/r.png"
"P" = "other/p.png"

[sound]
"BACK_BGM" = "Night View.mp3"
"BATTLE_BGM" = "City of Night.mp3"

[font]
"TITLE" = "优设标题黑.ttf"
"MENU" = "阿里巴巴普惠体.ttf"
"ATK" = "AtkDef.ttf"