[string]
SERVER_PLAYER_NAME = ""
SERVER_ADDRESS = ""
SERVER_PASS = ""
I18N = ""
[number]
CT_VOICE = 0.00
CT_CARD = 3
CT_DECK_MAIN = 60
CT_DECK_EX = 15
CT_DECK_SIDE = 15
[boolean]
DELETE_YPK = true
DELETE_DECK = true
EXIT_DECK = true
SWAP_BUTTON = true
SORT_DECK = true
DISRUPT_DECK = true
CLEAR_DECK = true
SELECT_SORT = true
SURRENDER = true
EXIT_SERVER = true
HIDDEN_NAME = false
HIDDEN_CHAT = false
[array]
LOADING_EXPANSION = []
