[ot]
0x1 = "ot_ocg"
0x2 = "ot_tcg"
0x3 = "ot_ocgtcg"
0x4 = "ot_custom"
0x8 = "ot_sc"

[attribute]
0x1 = "attr_earth"
0x2 = "attr_water"
0x4 = "attr_fire"
0x8 = "attr_wind"
0x10 = "attr_light"
0x20 = "attr_dark"
0x40 = "attr_divine"

[link]
0x40 = ["arrow-1-off", "arrow-1-on"]
0x80 = ["arrow-2-off", "arrow-2-on"]
0x100 = ["arrow-3-off", "arrow-3-on"]
0x8 = ["arrow-4-off", "arrow-4-on"]
0x20 = ["arrow-5-off", "arrow-5-on"]
0x1 = ["arrow-6-off", "arrow-6-on"]
0x2 = ["arrow-7-off", "arrow-7-on"]
0x4 = ["arrow-8-off", "arrow-8-on"]

[category]
0x1 = "category_destroySpellTrap"
0x2 = "category_destroyMonster"
0x4 = "category_banish"
0x8 = "category_sendToGraveyard"
0x10 = "category_returnToHand"
0x20 = "category_returnToDeck"
0x40 = "category_destroyHand"
0x80 = "category_destroyDeck"
0x100 = "category_draw"
0x200 = "category_search"
0x400 = "category_recovery"
0x800 = "category_position"
0x1000 = "category_control"
0x2000 = "category_changeAtkDef"
0x4000 = "category_piercing"
0x8000 = "category_repeatAttack"
0x10000 = "category_limitAttack"
0x20000 = "category_directAttack"
0x40000 = "category_specialSummon"
0x80000 = "category_token"
0x100000 = "category_raceRelated"
0x200000 = "category_attributeRelated"
0x400000 = "category_damageLP"
0x800000 = "category_recoverLP"
0x1000000 = "category_undestroyable"
0x2000000 = "category_ineffective"
0x4000000 = "category_counter"
0x8000000 = "category_gamble"
0x10000000 = "category_fusionRelated"
0x20000000 = "category_synchroRelated"
0x40000000 = "category_xyzRelated"
0x80000000 = "category_negateEffect"

[race]
0x1 = "race_warrior"
0x2 = "race_spell-caster"
0x4 = "race_fairy"
0x8 = "race_fiend"
0x10 = "race_zombie"
0x20 = "race_machine"
0x40 = "race_aqua"
0x80 = "race_pyro"
0x100 = "race_rock"
0x200 = "race_wind-beast"
0x400 = "race_plant"
0x800 = "race_insect"
0x1000 = "race_thunder"
0x2000 = "race_dragon"
0x4000 = "race_beast"
0x8000 = "race_beast-warrior"
0x10000 = "race_dinosaur"
0x20000 = "race_fish"
0x40000 = "race_sea-serpent"
0x80000 = "race_reptile"
0x100000 = "race_psycho"
0x200000 = "race_divine-beast"
0x400000 = "race_create-god"
0x800000 = "race_wyrm"
0x1000000 = "race_cyberse"
0x2000000 = "race_illusion"

[types]
0x1 = "cardType_monster"
0x10 = "type_normal"
0x12 = "spellTrapType_normal"
0x20 = "type_effect"
0x1000 = "type_tuner"
0x800 = "type_dual"
0x200000 = "type_flip"
0x400 = "type_union"
0x200 = "type_spirit"
0x400000 = "type_toon"
0x40 = "type_fusion"
0x2000 = "type_synchro"
0x800000 = "type_xyz"
0x1000000 = "type_pendulum"
0x80 = "type_ritual"
0x81 = "type_ritual"
0x82 = "spellTrapType_ritual"
0x2 = "cardType_spell"
0x4 = "cardType_trap"
0x10000 = "spellTrapType_quickplay"
0x20000 = "spellTrapType_continuous"
0x40000 = "spellTrapType_equip"
0x80000 = "spellTrapType_field"
0x100000 = "spellTrapType_counter"
0x4000000 = "type_link"
0x2000000 = "type_specialSummon"
0x4000 = "type_token"