name: build assets

on:
  push:
    tags:
      - 'assets*'
    
jobs:
  make-assets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
      
    - name: Install wget and unzip
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip p7zip-full p7zip-rar

    - name: Download Assets
      run: |
        cd .ci
        wget -O ygopro-database.zip https://github.com/mycard/ygopro-database/archive/refs/heads/master.zip
        unzip ygopro-database.zip

        mkdir -p cdb
        mkdir -p strings

        cp ygopro-database-master/locales/zh-CN/cards.cdb cdb/cards-zh-CN.cdb
        cp ygopro-database-master/locales/ko-KR/cards.cdb cdb/cards-ko-KR.cdb
        cp ygopro-database-master/locales/ja-JP/cards.cdb cdb/cards-ja-JP.cdb
        cp ygopro-database-master/locales/en-US_mdpro3/cards.cdb cdb/cards-en-US.cdb

        cp ygopro-database-master/locales/zh-CN/strings.conf strings/strings-zh-CN.conf
        cp ygopro-database-master/locales/ko-KR/strings.conf strings/strings-ko-KR.conf
        cp ygopro-database-master/locales/ja-JP/strings.conf strings/strings-ja-JP.conf
        cp ygopro-database-master/locales/en-US_mdpro3/strings.conf strings/strings-en-US.conf

        wget --no-check-certificate ${{ secrets.PICS_URL }} -O pics.zip
        unzip pics.zip

        date > version
        wget -O lflist.conf https://github.com/Fluorohydride/ygopro/raw/refs/heads/master/lflist.conf

        7z a -tzip -mx=9 assets.zip pics/ config/ strings/ cdb/ sound/ textures/ font/ lflist.conf version
    
    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: assets.zip
        retention-days: 7
        path: ./.ci/assets.zip

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: version
        retention-days: 7
        path: ./.ci/version

  update-gitcode:
    needs: [make-assets]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Upload to GitCode
        run: |
          pip install requests
          python .ci/update.py ${{ secrets.GITCODE_ACCESS_TOKEN }}

  upload:
    needs: [update-gitcode]
    name: upload-${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: assets.zip
          - target: version.txt
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: build

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'

    - name: PrePare
      run: |
        cp .ci/upload.py build/upload.py
        pip install requests

    - name: PrePare
      if: ${{ matrix.target == 'version.txt' }}
      run: |
          cd build/version
          mv version ../version.txt

    - name: PrePare
      if: ${{ matrix.target == 'assets.zip' }}
      run: |
          cd build
          mv assets.zip assets
          cd assets
          mv assets.zip ../assets.zip

    - name: Install wget and unzip
      run: |
        sudo apt-get update
        sudo apt-get install -y wget

    - name: Install privoxy
      run: |
        npm i -g pm2
        mkdir ss
        cd ss
        wget https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.24.0/shadowsocks-v1.24.0.x86_64-unknown-linux-gnu.tar.xz
        tar -xvf shadowsocks-v1.24.0.x86_64-unknown-linux-gnu.tar.xz
        chmod +777 sslocal
        pm2 start sslocal --name ss -- -b "127.0.0.1:1080" ${{ secrets.PROXY }}

    - name: Upload
      env:
        http_proxy: http://127.0.0.1:1080
        https_proxy: http://127.0.0.1:1080
      run: |
        cd build
        python upload.py ${{ secrets.GITCODE_ACCESS_TOKEN }} ${{ matrix.target }}

    - name: Stop Proxy
      if: always()
      run: pm2 stop all

  create-release:
    needs: [make-assets]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build

      - name: Delete old Release
        run: |
          TAG_NAME=assets-latest
          gh release delete "$TAG_NAME" --yes || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch --tags
          git tag -d assets-latest || true
          git push origin :refs/tags/assets-latest || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tag
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag assets-latest
          git push origin assets-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: assets-latest
          release_name: assets-latest
          draft: false
          prerelease: false

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/assets.zip/assets.zip
          asset_name: assets.zip
          asset_content_type: application/octet-stream