name: build YGOPro3

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    
jobs:
  push-gitcode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Set SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitcode.com >> ~/.ssh/known_hosts

      - name: Push to GitCode
        run: |
          git remote add gitcode git@gitcode.com:jwyxym/YGOPro3.git
          git fetch gitcode
          git checkout -b gitcode-main gitcode/main
          git merge origin/main
          git push gitcode gitcode-main:main

  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK and NDK
      uses: android-actions/setup-android@v3
      with:
        accept-android-sdk-licenses: true

    - name: Set Android Environment
      run: |
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
        echo "NDK_HOME=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/build-tools/34.0.0" >> $GITHUB_PATH

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.88.0

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Download assets
      uses: robinraju/release-downloader@v1.10
      with:
        tag: assets-latest
        fileName: "assets.zip"
        out-file-path: "./src-tauri/"
        
    - name: Rename assets
      run: mv ./src-tauri/assets.zip ./src-tauri/assets

    - name: Write Tauri Config
      run: |
        npm run json:build ${{ github.ref_name }}

    - name: NPM Init
      run: |
        npm ci
    
    - name: Android Init
      run: |
        npm run tauri:android:init

    - name: Android build
      run: |
        npm run tauri:android:build:sh

    - name: Decode Keystore File
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > YGOPro3.jks

    - name: Sign apk
      run: |
        mkdir build
        apksigner sign --ks ./YGOPro3.jks --ks-key-alias ${{ secrets.KEY_ALIAS }} --key-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --out ./build/YGOPro3.apk ./src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3.apk
        retention-days: 1
        path: ./build/YGOPro3.apk

  build-windows:
    name: build-windows-${{ matrix.target }}
    runs-on: ${{ matrix.run-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64
            run-on: windows-latest
          - target: aarch64
            run-on: windows-11-arm
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.88.0

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Download assets
      uses: robinraju/release-downloader@v1.10
      with:
        tag: assets-latest
        fileName: "assets.zip"
        out-file-path: "./src-tauri/"
        
    - name: Rename assets
      run: move src-tauri\assets.zip src-tauri\assets

    - name: Write Tauri Config
      shell: cmd
      run: |
        npm run json:build ${{ github.ref_name }}

    - name: NPM Init
      run: |
        npm ci

    - name: Windows build
      run: |
        npm run tauri:build
    
    - name: Copy
      shell: cmd
      run: |
        set "found_msi="
        set "found_exe="
        mkdir build

        for %%f in (.\src-tauri\target\release\bundle\msi\*) do (
            if not defined found_msi (
                copy "%%f" ".\build\YGOPro3.msi"
                set "found_msi=1"
            )
        )

        for %%f in (.\src-tauri\target\release\bundle\nsis\*) do (
            if not defined found_exe (
                copy "%%f" ".\build\YGOPro3.exe"
                set "found_exe=1"
            )
        )

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-windows-${{ matrix.target }}.exe
        retention-days: 1
        path: .\build\YGOPro3.exe

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-windows-${{ matrix.target }}.msi
        retention-days: 1
        path: .\build\YGOPro3.msi

  build-macos:
    name: build-macos-${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64
          - target: aarch64

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.88.0
        target: ${{ matrix.target }}-apple-darwin

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Download assets
      uses: robinraju/release-downloader@v1.10
      with:
        tag: assets-latest
        fileName: "assets.zip"
        out-file-path: "./src-tauri/"
        
    - name: Rename assets
      run: mv ./src-tauri/assets.zip ./src-tauri/assets

    - name: Write Tauri Config
      run: |
        npm run json:build ${{ github.ref_name }}

    - name: NPM Init
      run: |
        npm ci

    - name: Macos build
      run: |
        npm run tauri:build

    - name: Zip .app
      run: |
        cd ./src-tauri/target/release/bundle/macos/
        zip -r YGOPro3.app.zip ygopro3.app

    - name: Copy
      run: |
        mkdir -p ./build
        DMG_FILES=(./src-tauri/target/release/bundle/dmg/*.dmg)
        cp "${DMG_FILES[0]}" ./build/YGOPro3.dmg

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-macos-${{ matrix.target }}.dmg
        retention-days: 1
        path: ./build/YGOPro3.dmg

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-macos-${{ matrix.target }}.app.zip
        retention-days: 1
        path: ./src-tauri/target/release/bundle/macos/YGOPro3.app.zip

  build-linux:
    name: build-linux-${{ matrix.target }}
    runs-on: ${{ matrix.run-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64
            run-on: ubuntu-latest
          - target: aarch64
            run-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.18.0'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.88.0

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Download assets
      uses: robinraju/release-downloader@v1.10
      with:
        tag: assets-latest
        fileName: "assets.zip"
        out-file-path: "./src-tauri/"

    - name: Rename assets
      run: mv ./src-tauri/assets.zip ./src-tauri/assets

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          librsvg2-dev \
          libglib2.0-dev \
          libcairo2-dev \
          libpango1.0-dev \
          libatk1.0-dev \
          libgdk-pixbuf2.0-dev \
          build-essential \
          libssl-dev \
          pkg-config \
          libgtk-3-dev \
          xdg-utils

    - name: Write Tauri Config
      run: |
        npm run json:build ${{ github.ref_name }}

    - name: NPM Init
      run: |
        npm ci

    - name: Build
      run: |
        npm run tauri:build

    - name: Copy
      run: |
        mkdir -p ./build
        cp ./src-tauri/target/release/bundle/appimage/*.AppImage ./build/YGOPro3.AppImage
        cp ./src-tauri/target/release/bundle/deb/*.deb ./build/YGOPro3.deb
        cp ./src-tauri/target/release/bundle/rpm/*.rpm ./build/YGOPro3.rpm

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-linux-${{ matrix.target }}.deb
        retention-days: 1
        path: ./build/YGOPro3.deb

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-linux-${{ matrix.target }}.rpm
        retention-days: 1
        path: ./build/YGOPro3.rpm

    - name: Upload File
      uses: actions/upload-artifact@v4
      with:
        name: YGOPro3-linux-${{ matrix.target }}.AppImage
        retention-days: 1
        path: ./build/YGOPro3.AppImage

  create-release:
    needs: [build-android, build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build

      - name: Ensure release exists
        run: |
          gh release view release-latest || \
          gh release create release-latest --title "release-latest" --notes "Auto build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        run: |
          gh release upload release-latest $(find build -type f) --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-gitcode:
    runs-on: ubuntu-latest
    needs: [build-android, build-windows, build-macos, build-linux]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Upload to GitCode
        run: |
          cd .ci
          pip install requests
          python update.py ${{ secrets.GITCODE_ACCESS_TOKEN }}

  upload-version:
    runs-on: ubuntu-latest
    needs: [upload-gitcode]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: build

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'

      - name: Install wget and unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

      - name: Install privoxy
        run: |
          npm i -g pm2
          mkdir ss
          cd ss
          wget https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.24.0/shadowsocks-v1.24.0.x86_64-unknown-linux-gnu.tar.xz
          tar -xvf shadowsocks-v1.24.0.x86_64-unknown-linux-gnu.tar.xz
          chmod +777 sslocal
          pm2 start sslocal --name ss -- -b "127.0.0.1:1080" ${{ secrets.PROXY }}

      - name: Upload to GitCode
        env:
          http_proxy: http://127.0.0.1:1080
          https_proxy: http://127.0.0.1:1080
        run: |
          cd .ci
          pip install requests
          python write_version.py ${{ github.ref_name }}
          python upload.py ${{ secrets.GITCODE_ACCESS_TOKEN }} version.txt
          find ../build -type f -exec python upload.py ${{ secrets.GITCODE_ACCESS_TOKEN }} {} \;
          python upload.py ${{ secrets.GITCODE_ACCESS_TOKEN }} version.txt

      - name: Stop Proxy
        if: always()
        run: pm2 stop all